// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs.proto

package com.microservice.proto;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string object = 3;</code>
   * @return The object.
   */
  java.lang.String getObject();
  /**
   * <code>string object = 3;</code>
   * @return The bytes for object.
   */
  com.google.protobuf.ByteString
      getObjectBytes();
}
