// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs.proto

package com.microservice.proto;

public interface addLogsParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addLogsParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <code>string remark = 3;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 3;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();
}
