// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs.proto

package com.microservice.proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
